name = "LoopToVecs"
uuid = "6a3a6ab9-d92e-4ecd-8bd0-f0d9833b6572"
authors = ["Wenlan Luo <luowenlan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
